--- #YAML:1.0
name:                Win32-UrlCache
version:             0.05
abstract:            parse Internet Explorer's history/cache/cookies
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    Test::UseAllModules:           0
    Win32::API:                    0
    Win32::TieRegistry:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
